{% set name = "blackcellmagic" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 089b98d28aa647f2d86c3161b60cbf09793384ea94ceb1227f4f1d425db4002c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - black
    - ipython
    - python >={{ python_min }}

test:
  imports:
    - blackcellmagic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/csurfer/blackcellmagic
  summary: IPython wrapper to format cell using black.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
